services:
  app:
    build:
      context: .
      target: dist

    image: bbb-stress-test:latest

    working_dir: /app

    env_file:
      - .env

    user: "${DOCKER_USER:-1000}"

    shm_size: "2gb"

    cap_add:
      - SYS_ADMIN

    volumes:
      - ./audio.wav:/app/audio.wav:ro
      - ./webcam.y4m:/app/webcam.y4m:ro
      - ./screenshots:/app/screenshots
      - ./reports:/app/reports

    stdin_open: true
    tty: true
